/** Textos del motor de widgets. Se pueden reemplazar por pantalla con la prop `labels`. */
export const DEFAULT_LABELS = {
  customize: 'Personalizar',
  views: 'Vistas del inicio',
  customView: 'Personalizado',
  customViewHint: 'Tu diseño: lo armás con Personalizar.',
  useAsBase: 'Usar como base',
  useAsBaseHint: 'Copia esta vista a Personalizado para editarla y guardarla.',
  addWidget: 'Agregar widget',
  restore: 'Restaurar diseño',
  cancel: 'Cancelar',
  save: 'Guardar',
  saving: 'Guardando…',
  editingHint: 'Arrastrá las tarjetas, estiralas desde la esquina o usá el menú ⋮.',
  narrowHint: 'Para personalizar el inicio usá una pantalla más ancha.',
  narrowWhileEditing: 'Agrandá la ventana para seguir editando.',
  loadError: 'No pudimos cargar tu diseño guardado. Se muestra el de fábrica y la personalización queda deshabilitada.',
  confirmDiscard: '¿Descartar los cambios del diseño?',
  confirmLeave: 'Tenés cambios sin guardar en el diseño del inicio. ¿Salir igual?',
  confirmRestore: '¿Volver al diseño de fábrica? Podés cancelar después si no te convence.',
  saveErrorSuffix: 'Tus cambios siguen acá: podés volver a intentar.',
  conflict: 'El diseño se guardó desde otra pestaña o dispositivo. Tus cambios siguen acá: "Guardar" los aplica encima de esa versión y "Cancelar" te muestra la versión nueva.',
  catalogTitle: 'Agregar widgets',
  catalogOnScreen: 'En pantalla',
  catalogAdd: 'Agregar',
  menuFor: (title) => `Opciones de ${title}`,
  hide: 'Ocultar',
  move: 'Mover',
  moveLeft: 'A la izquierda',
  moveRight: 'A la derecha',
  moveUp: 'Arriba',
  moveDown: 'Abajo',
  size: 'Tamaño',
  wider: 'Más ancho',
  narrower: 'Más angosto',
  taller: 'Más alto',
  shorter: 'Más bajo',
  visual: 'Visualización',
  visuals: { bars: 'Barras', line: 'Línea', pie: 'Torta' },
};
